--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Atomization/Events
branches:
- master
projects:
  Events:
    path: ""
    libs: 
      - src: poggit/libasynql/libasynql
        version: ^3.0
      - src: Atomization/gui/gui
        version: ^1.0.1
...
